version: '3.8'

services:
  app:
    container_name: appnation-identity-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    restart: unless-stopped
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_ACCESS_EXPIRATION_TIME=${JWT_ACCESS_EXPIRATION_TIME}
    volumes:
      - ./private.pem:/usr/app/private.pem
    networks:
      - appnation-network

  appnation-network:
    driver: bridge

